### ISSUE TITLE
129th Member Meeting Topics

### ISSUE THREAD

**Issue by RyanAhola** [opengeospatial/GeoDataCube-SWG#2]
The 129th OGC Member Meeting will be in Montreal from June 17-21, 2024. The GeoDataCube SWG chairs plan to host a SWG session during this meeting. Please comment on topics you would like to see discussed during the session.

**Comment by chris-little** [comment]
How about discussing the use of a [Pub-Sub approach](https://portal.ogc.org/files/?artifact_id=107070&version=1 )  or other Async mechanisms for demanding queries or processes?

**Comment by jerstlouis** [comment]
@RyanAhola 

I suggest that we should focus on considering the results of Testbed 19 GDC, and starting to make decisions or plan actions to move things forward on some of the open issues raised that I just filed in the issue tracker (several of them originate from the Usability Review Critical Feedback). 

Perhaps in this order: #8 / #1 , #7 , #6 / #3, #5, #9, #4

We previously briefly brough up these issues in the SWG, but did not really discuss them in detail or arrive at any decision or action to move things forward.

Progress on all this would be particularly useful to inform and guide the Testbed 20 GeoDataCube thread kickoff discussions planned for the following day.

@chris-little regarding async mechanism, see #9 .
I can think of at least two ways in how Pub-Sub could be used:
- To notify of the completion of a completed batched async processing job
- To notify of potential changes to the results of a virtual GeoDataCube (e.g., one accessible using OGC API - Processes - Part 3: Workflows "Collection Output", where processing is done on demand), based on changes to the underlying input collections and/or processes and/or workflow definition, so that data can be requested again for an Area/Time/Resolution of Interest.
